// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BlZr3R2vbmgzzmaBMzMY224HLBdBJ6U',
    appId: '1:508464754651:web:478a993181a8fc5c0f01fe',
    messagingSenderId: '508464754651',
    projectId: 'tqrnotifications',
    authDomain: 'tqrnotifications.firebaseapp.com',
    storageBucket: 'tqrnotifications.appspot.com',
    measurementId: 'G-4E33W4K363',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPbznGTRIf5gAS5F5bFrahaIpHgtvZ4jc',
    appId: '1:508464754651:android:d7e2a00ee94393580f01fe',
    messagingSenderId: '508464754651',
    projectId: 'tqrnotifications',
    storageBucket: 'tqrnotifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJT1PNLoHqZpt8WjBsgAoSapLN_ZLlulw',
    appId: '1:508464754651:ios:dbc29b67e302d7f70f01fe',
    messagingSenderId: '508464754651',
    projectId: 'tqrnotifications',
    storageBucket: 'tqrnotifications.appspot.com',
    iosClientId: '508464754651-h42c8le0donm57860e1h7ul6n8vsuubr.apps.googleusercontent.com',
    iosBundleId: 'com.sazent.tqrfamily',
  );
}
